import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Navbar from "../src/components/Navbar"
import { ReactTypical } from "@deadcoder0904/react-typical"
import TabScroll from "../src/components/TabScroll"

import JSSVG from "@/public/javascript.svg"
import TSSVG from "@/public/typescript.svg"
import PythonSVG from "@/public/python.svg"
import GolangSVG from "@/public/golang.svg"
import JavaSVG from "@/public/java.svg"
import ReactSVG from "@/public/react.svg"
import VueSVG from "@/public/vuejs.svg"
import FlutterSVG from "@/public/flutter.svg"
import NodeJSSVG from "@/public/nodejs.svg"
import GraphQLSVG from "@/public/graphql.svg"
import GoFiberSVG from "@/public/fiber.svg"
import MongoDBSVG from "@/public/mongodb.svg"
import PostgresQLSVG from "@/public/postgresql.svg"
import RedisSVG from "@/public/redis.svg"
import MySqlSVG from "@/public/mysql.svg"
import FirebaseSVG from "@/public/firebase.svg"

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Pankorn&apos;s Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="sm:px-56 px-6">
				<Navbar />
				<div className="min-h-[90vh] pt-32">
					<div className="flex sm:justify-between sm:items-center flex-col sm:flex-row">
						<div className="sm:w-1/2 w-full sm:order-first order-last mt-12 sm:mt-0">
							<div className="font-bold uppercase text-center">
								<h1 className="text-5xl">Hi, I am Pankorn.</h1>
								<ReactTypical
									steps={[
										"Web Developer 🌐",
										2000,
										"Mobile Developer 📱",
										2000,
										"Backend Developer 💾",
										2000,
										"Full Stack Developer 💻",
										3000,
									]}
									wrapper="div"
									className="text-3xl h-12 text-orange-500 mt-3 inline"
									loop={Infinity}
								/>
								<span className="text-3xl font-light ml-1 animate-ping">|</span>
							</div>

							<p className="mt-3">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
								enim ad minim veniam, quis nostrud exercitation ullamco laboris
								nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
							</p>
						</div>
						<div>
							<Image
								src="/me.jpeg"
								width={300}
								height={300}
								objectFit="cover"
								alt="pankorn"
								className="rounded-full"
							/>
						</div>
					</div>
				</div>

				<TabScroll
					className="sm:mt-0 mt-12"
					tabs={[
						{ title: "Personal Info", id: "personal_info" },
						{ title: "Languages", id: "languages" },
						{ title: "Education", id: "education" },
						{ title: "Programming Skills", id: "programming_skills" },
						{ title: "Projects", id: "projects" },
					]}
					contents={[
						{
							id: "personal_info",
							content: (
								<div className="flex flex-col justify-center">
									<div className="">Pankorn Chantarod</div>
									<div>24 OCT. 2000</div>
									<div>Chiang Rai, Thailand</div>
								</div>
							),
						},
						{
							id: "languages",
							content: (
								<div>
									<div>Thai (Native)</div>
									<div>English (Intermediate)</div>
								</div>
							),
						},
						{
							id: "education",
							content: (
								<div className="flex justify-between">
									<div className="flex items-start">
										<div className="w-4 h-4 bg-orange-500 rounded-full mt-1 mr-3" />
										<div className="">
											<div className="text-orange-500 font-medium text-lg">
												University of Phayao
											</div>
											<span>Software Engineering</span>
										</div>
									</div>
									<div className="bg-orange-500 rounded-full h-fit text-white px-3 py-1 text-xs">
										2019 - 2022
									</div>
								</div>
							),
						},
						{
							id: "programming_skills",
							content: (
								<div className="space-y-6 border-b pb-3">
									<h5 className="text-xl font-medium text-orange-500 mb-3">
										Programming Languages
									</h5>
									<div className="flex space-x-6 pb-3">
										<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
											<JSSVG className="w-16" />
											<span>JavaScript</span>
										</div>

										<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
											<TSSVG className="w-16" />
											<span>TypeScript</span>
										</div>

										<div className="flex flex-col items-center">
											<PythonSVG className="w-16 hover:text-orange-500 transition-all duration-200 ease-in-outw-16" />
											<span>Python</span>
										</div>

										<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
											<GolangSVG className="w-16" />
											<span>Golang</span>
										</div>

										<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
											<JavaSVG className="w-16" />
											<span>Java</span>
										</div>
									</div>

									<h5 className="text-xl font-medium text-orange-500 mb-3">
										Programming Frameworks
									</h5>
									<div className="ml-3">
										<h6 className="text-lg font-medium text-orange-500 mb-3">
											Front-end
										</h6>
										<div className="">
											<h6 className="text-lg font-medium text-orange-500 mb-3 ml-3">
												WEB
											</h6>
											<div className="flex space-x-6 ml-3">
												<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
													<ReactSVG className="w-16" />
													<span>React JS & Next JS</span>
												</div>
												<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
													<VueSVG className="w-16" />
													<span>Vue JS & Nuxt JS</span>
												</div>
											</div>

											<h6 className="text-lg font-medium text-orange-500 my-3 ml-3">
												Mobile
											</h6>
											<div className="flex space-x-6 ml-3">
												<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
													<ReactSVG className="w-16" />
													<span>React-Native</span>
												</div>
												<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
													<FlutterSVG className="w-16" />
													<span>Flutter</span>
												</div>
											</div>
										</div>

										<h6 className="text-lg font-medium text-orange-500 my-3 ml-3">
											Back-end
										</h6>
										<div className="flex space-x-6 ml-3">
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<NodeJSSVG className="w-16" />
												<span>Express JS</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<GraphQLSVG className="w-16" />
												<span>Apollo Express</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<GoFiberSVG className="h-16" />
												<div>Go Fiber</div>
											</div>
										</div>

										<h6 className="text-lg font-medium text-orange-500 my-3 ml-3">
											Databases
										</h6>
										<div className="flex space-x-6 ml-3">
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<MongoDBSVG className="w-16" />
												<span>MongoDB</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<PostgresQLSVG className="w-16" />
												<span>PostgresQL</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<MySqlSVG className="w-16" />
												<span>MySql</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<RedisSVG className="w-16" />
												<span>Redis</span>
											</div>
											<div className="flex flex-col items-center hover:text-orange-500 transition-all duration-200 ease-in-out">
												<FirebaseSVG className="w-16" />
												<span>Firestore</span>
											</div>
										</div>
									</div>
								</div>
							),
						},
						{
							id: "projects",
							content: (
								<div>
									<h5 className="text-xl font-medium text-orange-500 mb-3">
										Projects
									</h5>
									<div className="ml-3">
										<a
											href="https://sharekan.netlify.app/"
											target="_blank"
											rel="noopener noreferrer"
											className="underline underline-offset-4 text-orange-500"
										>
											Sharekan
										</a>
										<div className="text-sm ml-3 mt-2 mb-3">
											Lorem ipsum dolor sit amet, consectetur adipiscing elit,
											sed do eiusmod tempor
										</div>
										<div>
											<h6 className="mb-3">Tech Stacks</h6>
											<div className="flex space-x-12 ml-3">
												<div>
													<div>Frontend</div>
													<ul className="list-disc ml-6">
														<li>Next JS</li>
														<li>Apollo Client</li>
														<li>Tailwind CSS</li>
														<li>Next Auth</li>
														<li>Netlify</li>
													</ul>
												</div>

												<div>
													<div>Backend</div>
													<ul className="list-disc ml-6">
														<li>Apollo Express</li>
														<li>PostgresQL</li>
														<li>Heroku</li>
													</ul>
												</div>
											</div>
											<h6 className="my-3">Source code</h6>
											<div className="flex flex-col ml-3 space-y-2">
												<a
													href="https://github.com/pankornch/sharekan-client"
													target="_blank"
													rel="noopener noreferrer"
													className="underline underline-offset-4 text-orange-500"
												>
													Frontend
												</a>
												<a
													href="https://github.com/pankornch/sharekan-api"
													target="_blank"
													rel="noopener noreferrer"
													className="underline underline-offset-4 text-orange-500"
												>
													Backend
												</a>
											</div>
										</div>
									</div>
								</div>
							),
						},
					]}
				/>

				<div>
					<div>Tournaments & Activities</div>
					<ul>
						<li>
							<div>Startup Thailand League 2020</div>
							<span>Evoligence</span>
							<span>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor
							</span>
						</li>
						<li>
							<div>Research to Market 2020</div>
							<span>Evoligence</span>
							<span>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor
							</span>
						</li>
						<li>
							<div>Bootcamp 20Scoops CNX 2021</div>
							<span>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
								eiusmod tempor
							</span>
						</li>
					</ul>
				</div>
			</main>
		</div>
	)
}

export default Home
